python launcher_scripts/run_from_config.py configs/iceberg/msg_all/dag_inten_train_msg_all_iceberg.yaml
python launcher_scripts/run_from_config.py configs/iceberg/msg_all/dag_inten_contr_finetune_msg_all_iceberg.yaml
