python launcher_scripts/run_from_config.py configs/iceberg_transformer/joint_train_nist20.yaml

# contrastive finetune
python launcher_scripts/run_from_config.py configs/iceberg_transformer/joint_contr_finetune_nist20.yaml