python launcher_scripts/run_from_config.py configs/iceberg_transformer/inten_train_nist20.yaml

# contrastive finetune
python launcher_scripts/run_from_config.py configs/iceberg_transformer/inten_contr_finetune_nist20.yaml