name: ms-gen
channels:
- pytorch
- nvidia
- dglteam/label/th24_cu118
- conda-forge
- pyg
- bioconda
dependencies:
- python=3.10.*
- cython
- matplotlib=3.10.*
- rdkit=2025.03.*
- pytorch-lightning=1.6.*
- pip=25.2
- ipykernel=6.29.*
- pytorch=2.4.1
- pytorch-cuda=11.8
- einops
- nb_conda_kernels=2.3.*
- seaborn=0.13.*
- ray-tune
- pytorch-scatter
- pytorch-sparse
- dgl
- cudatoolkit=11.8
