[project]
name = "ms-gen"
version = "0.1.0"
description = "A package for computational tandem mass spectrometry simulation."
authors = [
    { name = "Sam Goldman", email = "samlg@mit.edu" },
    { name = "Runzhong Wang", email = "rwang@mit.edu" },
    { name = "Mrunali Manjrekar", email = "mrunali@mit.edu" },
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
    "scikit-learn",
    "pathos",
    "cython",
    "CairoSVG",
    "ipdb",
    "pubchempy",
    "omegaconf",
    "h5py",
    "matplotlib",
    "rdkit",
    "ipykernel",
    "einops", 
    "pytorch-lightning",
    "pygmtools", 
    "ray",
    "ray[tune]>=2.49.1",
    "dgl==2.4.0", 
    "torch-scatter @ https://data.pyg.org/whl/torch-2.4.0%2Bcu121/torch_scatter-2.1.2+pt24cu121-cp310-cp310-linux_x86_64.whl",
    "torch-sparse @ https://data.pyg.org/whl/torch-2.4.0%2Bcu121/torch_sparse-0.6.18+pt24cu121-cp310-cp310-linux_x86_64.whl",
    "torch==2.4.0",
    "torchaudio==2.4.0", 
    "torchvision==0.19.0",
    "torch-geometric",
    "seaborn",
    "MKL"
]



[tool.uv.sources]
pygmtools = { git = "https://github.com/Thinklab-SJTU/pygmtools.git" }

[tool.uv]
# no torch-related wheels needed
find-links = [
    "https://data.pyg.org/whl/torch-2.4.0+cpu.html",
    "https://data.pyg.org/whl/torch-2.4.0+cu121.html",
    "https://data.dgl.ai/wheels/repo.html",
    "https://data.dgl.ai/wheels/cu121/repo.html",
    "https://data.dgl.ai/wheels/torch-2.4/cu121/repo.html"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.extra-build-dependencies]
ms-gen = ["numpy", "Cython"]

