launcher_args: {experiment_name: 2023_01_16_dag_bce_weight_sweep_2, #dag_inten, # dag_inten_gold_dag, 
  script_name: "src/ms_pred/dag_pred/train_inten.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local_parallel,
  visible_devices: [0,1,2, 3] #[0, 1, 2]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, #nodelist: 'node[1236]',
    time: '1-18:00:00'}
  debug: [false]
  debug-overfit: [false]
  gpu: [true]

  seed: [1]
  num-workers: [8] #[20]
  batch-size: [32]
  max-epochs: [200]

  dataset-name: [canopus_train_public]
  split-name: [split_1.tsv] #[split_1.tsv, split_2.tsv, split_3.tsv]

  learning-rate: [0.00076]
  lr-decay-rate: [0.78]

  dropout: [0.3]
  mpnn-type: [GGNN]
  pe-embed-k: [19]
  pool-op: [avg]
  hidden-size: [128]
  weight-decay: [1.0e-06]
  layers: [5]
  frag-attn-layers: [2]
  inject-early: [False]
  root-encode: [gnn]
  set-layers: [0]
  loss-fn: [hurdle_norm]
  magma-dag-folder: [results/dag_gen/split_1/preds_train_inten_0005/]

iterative_args:
  - save-dir: ["9"]
    bce-weight: [0.9]
  - save-dir: ["5"]
    bce-weight: [0.5]
  - save-dir: ["01"]
    bce-weight: [0.01]
  - save-dir: ["99"]
    bce-weight: [0.99]

    #magma-dag-folder: [results/dag_gen/split_1/preds_train_inten_01/]
      #-  split-name: [split_2.tsv]
      #   save-dir: [split_2]
      #   magma-dag-folder: [results/dag_gen/split_2/preds_train_inten_01/]
      #-  split-name: [split_3.tsv]
      #   save-dir: [split_3]
      #   magma-dag-folder: [results/dag_gen/split_3/preds_train_inten_01/]

  #-  split-name: [split_1.tsv]
  #   save-dir: [split_1]
  #   magma-dag-folder: [data/spec_datasets/canopus_train_public/magma_outputs/magma_tree/]
  #
  
  #-  split-name: [split_1.tsv]
  #   save-dir: [split_1]
  #   magma-dag-folder: [results/dag_gen/split_1/preds_train_inten_02/]
