launcher_args: {experiment_name: dag_gen, #dag_gen_,
  script_name: "src/ms_pred/dag_pred/train_gen.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local,
  visible_devices: [0]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, #nodelist: 'node[1236]',
    time: '1-18:00:00'}
  debug: [false]
  gpu: [true]

  seed: [1]
  num-workers: [8] #[20]
  batch-size: [32]
  max-epochs: [200]

  dataset-name: [canopus_train_public]
  split-name: [split_1.tsv] #[split_1.tsv, split_2.tsv, split_3.tsv]

  learning-rate: [0.000389]
  lr-decay-rate: [0.778048]

  dropout: [0.1]
  mpnn-type: [GINE]
  pe-embed-k: [10]
  pool-op: [avg]
  set-layers: [0]
  hidden-size: [128]
  weight-decay: [1.0e-07]
  layers: [5]

  # Trying to run with FP encoding
  root-encode: [gnn]
  inject-early: [True]

iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1]
     #-  split-name: [split_2.tsv]
     #   save-dir: [split_2]
     #-  split-name: [split_3.tsv]
     #   save-dir: [split_3]
