launcher_args: {experiment_name: ffn_baseline_100, #ffn_baseline,
  script_name: "src/ms_pred/ffn_pred/train.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local, #local_parallel,
  visible_devices: [0, 1, 2]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, #nodelist: 'node[1236]',
    time: '1-18:00:00'}
  debug: [false]
  gpu: [true]

  seed: [1]
  num-workers: [16] #[20]
  batch-size: [128]
  max-epochs: [200]

  dataset-name: [canopus_train_public]
  split-name: [split_1.tsv] #[split_1.tsv, split_2.tsv, split_3.tsv]

  learning-rate: [0.000118]
  lr-decay-rate: [0.828]
  num-bins: [3000] 
  loss-fn: [cosine]
  #loss-fn: [mse]

  dropout: [0.2]
  hidden-size: [512]
  use-reverse: [true]
  weight-decay: [1.0e-7]
  layers: [2]

  form-dir-name: ['subform_100']

iterative_args:
  #-  split-name: [split_1.tsv]
  #   save-dir: [split_1]
  #-  split-name: [split_2.tsv]
  #   save-dir: [split_2]
  #-  split-name: [split_3.tsv]
  #   save-dir: [split_3]

  -  split-name: [split_1.tsv]
     save-dir: [split_1]
