# Predict forms
launcher_args: {experiment_name: dag_canopus_train_public, 
  script_name: "src/ms_pred/dag_pred/predict_gen.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local, #local_parallel,
  visible_devices: [1] #,2,3] #,1,2]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, #nodelist: 'node[1236]',
    time: '1-18:00:00'}
  debug: [false]
  gpu: [false]

  batch-size: [64]
  dataset-name: [canopus_train_public]

  num-workers: [0]
  threshold: [0.0]
  max-nodes: [100]

iterative_args:
   -  split-name: [split_1.tsv]
      checkpoint-pth: [results/dag_canopus_train_public/split_1/version_0/best.ckpt]
      save-dir: [split_1/preds_train_100]
      threshold: [0.0]
      max-nodes: [100]
