# please modify the following configuration accordingly to your own environment
# you could create multiple entries for different hostnames

example: # modify example to your hostname
  python_path: '/path/to/your/python'
  gen_ckpt: '/path/to/iceberg_nist20/split_1_rnd1/ckpt/gen/best.ckpt'
  inten_ckpt: '/path/to/iceberg_nist20/split_1_rnd1/ckpt/inten_contr/best.ckpt'
  conf_models:  # confidence models. Could be empty if you don't want to use them
    1: '/path/to/iceberg_nist20/split_1_rnd1/retrieval_confidence/lr_conf_k1.joblib'
    3: '/path/to/iceberg_nist20/split_1_rnd1/retrieval_confidence/lr_conf_k3.joblib'
    5: '/path/to/iceberg_nist20/split_1_rnd1/retrieval_confidence/lr_conf_k5.joblib'
  conf_thresholds:  # medium and high confidence thresholds
    1: [ 0.810, 0.9375 ]
    3: [ 0.470, 0.7100 ]
    5: [ 0.305, 0.5725 ]
  cuda_devices: 0  # == CUDA_VISIBLE_DEVICES, set null if you want to use CPU
  batch_size: 128
  num_cpu_workers: 16
  num_gpu_workers: 2  # adjust batch_size and num_workers to maximize your GPU util within your GPU memory
  sparse_k: 100  # number of predicted peaks by ICEBERG-Score
  max_nodes: 100  # number of nodes in fragmentation DAG predicted by ICEBERG-Gen
  threshold: 0.0
  binned_out: False
  ppm: 20
  num_bins: 15000
  dist_func: 'entropy'
  instrument: 'Orbitrap'

# below are example configurations in Coley group nodes
molgpu01:
  python_path: '/home/runzhong/mambaforge/envs/ms-gen-torch24/bin/python'
  gen_ckpt: '/home/runzhong/ms-models/iceberg_results_20260413/iceberg_nist23/split_1_rnd1/ckpt/gen/best.ckpt'
  inten_ckpt: '/home/runzhong/ms-models/iceberg_results_20260413/iceberg_nist23/split_1_rnd1/ckpt/inten_contr/best.ckpt'
  conf_models:
    1: '/home/runzhong/ms-models/iceberg_results_20260413/iceberg_nist23/split_1_rnd1/retrieval_confidence/lr_conf_k1.joblib'
    3: '/home/runzhong/ms-models/iceberg_results_20260413/iceberg_nist23/split_1_rnd1/retrieval_confidence/lr_conf_k3.joblib'
    5: '/home/runzhong/ms-models/iceberg_results_20260413/iceberg_nist23/split_1_rnd1/retrieval_confidence/lr_conf_k5.joblib'
  conf_thresholds:
    1: [ 0.810, 0.9375 ]
    3: [ 0.470, 0.7100 ]
    5: [ 0.305, 0.5725 ]
  cuda_devices: [1]
  batch_size: 128
  num_cpu_workers: 16
  num_gpu_workers: 2
  sparse_k: 100
  max_nodes: 100
  threshold: 0.0
  binned_out: False
  ppm: 20
  num_bins: 15000
  dist_func: 'entropy'
  instrument: 'Orbitrap'

molgpu02:
  clone: molgpu01

molgpu03:
  clone: molgpu01

molgpu04:
  clone: molgpu01

molgpu05:
  clone: molgpu01

molgpu06:
  clone: molgpu01
