launcher_args: {experiment_name: scarf_inten_canopus_train_public,
  script_name: "src/ms_pred/scarf_pred/train_inten.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local,
  visible_devices: [0]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, 
     nodelist: 'node[1236]', time: '1-18:00:00'}
  debug: [false]
  gpu: [true]

  seed: [1]
  num-workers: [10]
  batch-size: [32]
  max-epochs: [200]

  dataset-name: [canopus_train_public]
  split-name: [split_1.tsv]

  learning-rate: [0.000308]
  lr-decay-rate: [0.962]

  dropout: [0.2]
  mpnn-type: [GGNN]
  pe-embed-k: [7]
  pool-op: [attn]
  hidden-size: [512]
  weight-decay: [0]
  set-layers: [0]
  form-set-layers: [2]
  mlp-layers: [2]
  gnn-layers: [3]
  embedder: [abs-sines]
  binned-targs: [true] 
  no-mol: [false]
  info-join: [concat]
  loss-fn: [cosine]
  embed-adduct: [true]

iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd1]
     formula-folder: [results/scarf_canopus_train_public/split_1_rnd1/preds_train_300_inten/]
     seed: [1]

  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd2]
     formula-folder: [results/scarf_canopus_train_public/split_1_rnd2/preds_train_300_inten/]
     seed: [2]

  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd3]
     formula-folder: [results/scarf_canopus_train_public/split_1_rnd3/preds_train_300_inten/]
     seed: [3]
