launcher_args: {experiment_name: ffn_baseline_nist_magma, #ffn_baseline,
  script_name: "src/ms_pred/ffn_pred/train.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local, #local_parallel,
  visible_devices: [0]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, #nodelist: 'node[1236]',
    time: '1-18:00:00'}
  debug: [false]
  gpu: [true]

  seed: [1]
  num-workers: [16]
  batch-size: [128]
  max-epochs: [200]

  dataset-name: [nist20]
  split-name: [split_1.tsv]

  learning-rate: [0.000118]
  lr-decay-rate: [0.828]
  num-bins: [10000]
  loss-fn: [cosine]

  dropout: [0.2]
  hidden-size: [512]
  use-reverse: [true]
  weight-decay: [1.0e-7]
  layers: [2]

  #form-dir-name: ['no_subform']
  form-dir-name: ['magma_subform_50']

iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1]
