# Predict dags
launcher_args: {experiment_name: scarf, #dag_gen_,
  script_name: "src/ms_pred/scarf_pred/predict_gen.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local, #local_parallel,
  visible_devices: [2] #,2,3] #,1,2]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, #nodelist: 'node[1236]',
    time: '1-18:00:00'}
  debug: [false]
  gpu: [True]

  batch-size: [32]
  dataset-name: [canopus_train_public]

  num-workers: [0]
  threshold: [0.0]
  max-nodes: [100]

iterative_args:

  #-  split-name: [split_1.tsv]
  #   checkpoint: [results/scarf/split_1/version_0/best.ckpt]
  #   save-dir: [split_1/preds_train_250]
  #   threshold: [0.000]
  #   max-nodes: [250]

  -  split-name: [split_1.tsv]
     checkpoint: [results/scarf/split_1/version_0/best.ckpt]
     save-dir: [split_1/preds_train_500]
     threshold: [0.000]
     max-nodes: [500]

     #-  split-name: [split_1.tsv]
     #   checkpoint: [results/scarf/split_1/version_0/best.ckpt]
     #   save-dir: [split_1/preds_train_1000]
     #   threshold: [0.000]
     #   max-nodes: [1000]

     #-  split-name: [split_2.tsv]
     #   checkpoint: [results/scarf/split_2/version_0/best.ckpt]
     #   save-dir: [split_2/preds_train_250]
     #   threshold: [0.000]
     #   max-nodes: [250]

  -  split-name: [split_2.tsv]
     checkpoint: [results/scarf/split_2/version_0/best.ckpt]
     save-dir: [split_2/preds_train_500]
     threshold: [0.000]
     max-nodes: [500]

     #-  split-name: [split_2.tsv]
     #   checkpoint: [results/scarf/split_2/version_0/best.ckpt]
     #   save-dir: [split_2/preds_train_1000]
     #   threshold: [0.000]
     #   max-nodes: [1000]

     #-  split-name: [split_3.tsv]
     #   checkpoint: [results/scarf/split_3/version_0/best.ckpt]
     #   save-dir: [split_3/preds_train_250]
     #   threshold: [0.000]
     #   max-nodes: [250]

  -  split-name: [split_3.tsv]
     checkpoint: [results/scarf/split_3/version_0/best.ckpt]
     save-dir: [split_3/preds_train_500]
     threshold: [0.000]
     max-nodes: [500]

     #-  split-name: [split_3.tsv]
     #   checkpoint: [results/scarf/split_3/version_0/best.ckpt]
     #   save-dir: [split_3/preds_train_1000]
     #   threshold: [0.000]
     #   max-nodes: [1000]
