launcher_args: {experiment_name: autoregr_nist20,
  script_name: "src/ms_pred/autoregr_gen/train.py",
  slurm_script: launcher_scripts/generic_slurm.sh, 
  launch_method: local,
  visible_devices: [2]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: forward_train, mem-per-cpu: 8G, 
    nodelist: 'node[1236]', time: '1-18:00:00'}
  debug: [false]
  debug-overfit: [false]
  gpu: [true]

  seed: [1]
  num-workers: [10]
  batch-size: [64]
  max-epochs: [200]

  dataset-name: [nist20]
  split-name: [split_1.tsv]

  use-reverse: [true]
  formula-folder: [magma_subform_50]
  embedder: [abs-sines]
  embed-adduct: [true]

  # Hyperparameters
  learning-rate: [0.0009]
  lr-decay-rate: [0.85]

  dropout: [0.2]
  mpnn-type: [GGNN]
  pe-embed-k: [20]
  pool-op: [avg]
  hidden-size: [512]
  weight-decay: [1.0e-06]
  rnn-layers: [3]
  set-layers: [0]
  gnn-layers: [1]


iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd1]
     seed: [1]
  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd2]
     seed: [2]
  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd3]
     seed: [3]
