launcher_args: {experiment_name: frag_only_nist20,
  script_name: "src/ms_pred/iceberg_transformer/train_frag.py",
  slurm_script: launcher_scripts/generic_slurm.sh,
  launch_method: local,
  visible_devices: [0]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: frag_only_train, mem-per-cpu: 8G,
    time: '1-12:00:00'}
  debug: [false]
  gpu: [true]

  seed: [1]
  num-workers: [16]
  batch-size: [32]
  max-epochs: [150]

  dataset-name: [nist20]
  split-name: [split_1.tsv]

  learning-rate: [0.0001]
  lr-decay-rate: [0.9]
  weight-decay: [0]

  dropout: [0]
  hidden-size: [512]
  layers: [5]
  max-breakpoints: [100]
  pe-embed-k: [0]
  include-unassigned: [False]

  root-encode: [graphormer]
  embed-elem-group: [True]
  embed-adduct: [True]
  embed-collision: [True]
  add-hs: [true]
  encode-form: [true]
  sk-tau: [0.05]
  linsat-tau: [15]
  multi-hop-max-dist: [10]
  num-edge-dis: [10]
  encoder-layers: [0]
  decoder-layers: [4]
  enable-aux-loss: [true]
  enable-decoder-norm: [false]
  warmup: [1000]

iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd1]
     seed: [1]
