launcher_args: {experiment_name: frag_only_nist20,
  script_name: "src/ms_pred/iceberg_transformer/test_frag.py",
  slurm_script: launcher_scripts/generic_slurm.sh,
  launch_method: local,
  visible_devices: [0]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: frag_only_test, mem-per-cpu: 8G,
    time: '1-12:00:00'}
  debug: [false]
  gpu: [true]

  seed: [1]
  num-workers: [16]
  batch-size: [32]
  max-epochs: [150]

  dataset-name: [nist20]
  split-name: [split_1.tsv]

  learning-rate: [0.0001]
  lr-decay-rate: [0.825]
  weight-decay: [0.0]

  dropout: [0.1]
  hidden-size: [256]
  layers: [4]
  max-frags: [100]
  pe-embed-k: [10]

  root-encode: [graphormer]
  embed-elem-group: [True]
  add-hs: [true]
  multi-hop-max-dist: [5]
  num-edge-dis: [10]
  test-checkpoint: ["results/frag_only_nist20/split_1_rnd1/version_37/best.ckpt"]

iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd1]
     seed: [1]
