launcher_args: {experiment_name: joint_train_nist20,
  script_name: "src/ms_pred/iceberg_transformer/train_joint.py",
  slurm_script: launcher_scripts/generic_slurm.sh,
  launch_method: local,
  visible_devices: [0]
}
universal_args:
  _slurm_args:
  - {_num_gpu: 1, cpus-per-task: 7, job-name: joint_train, mem-per-cpu: 8G,
    time: '1-12:00:00'}
  debug: [False]
  gpu: [true]

  seed: [1]
  num-workers: [16]
  batch-size: [32]
  max-epochs: [200]
  min-epochs: [0]

  dataset-name: [nist20]
  dataset-labels: [labels.tsv]
  magma-folder: [magma_outputs]
  split-name: [split_1.tsv]

  learning-rate: [0.0001]
  lr-decay-rate: [0.95]
  weight-decay: [0.0]

  inten-dropout: [0.05]
  frag-dropout: [0]
  inten-hidden-size: [512]
  frag-hidden-size: [512]
  embed-elem-group: [True]
  add-hs: [True]
  embed-adduct: [True]
  embed-collision: [True]
  encode-forms: [True]
  inten-graphormer-layers: [4]
  inten-decoder-layers: [3]
  inten-encoder-layers: [3]
  frag-graphormer-layers: [5]
  frag-encoder-layers: [0]
  frag-decoder-layers: [4]
  max-broken-bonds: [6]
  max-breakpoints: [100]
  multi-hop-max-dist: [10]
  num-edge-dis: [10]
  enable-aux-loss: [True]
  enable-decoder-norm: [False]
  sk-tau: [0.05]
  linsat-tau: [15]
  inten-weight: [1]
  frag-weight: [0.1]
  magma-warmup-steps: [5000]
  magma-decay-rate: [0.9]
  magma-decay-steps: [5000]
  warmup: [1000]
  binned-targs: [True]
  inten-loss-fn: [cosine]
  contr-loss-fn: [entropy]
  contr-weight: [1]

iterative_args:
  -  split-name: [split_1.tsv]
     save-dir: [split_1_rnd1]
     seed: [1]
